services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: projecthub-api
    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: projecthub-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=projecthub
      - POSTGRES_PASSWORD=project123
      - POSTGRES_DB=projecthub

    restart: unless-stopped
